# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: ais7896-hue.KyteShelf
PackageVersion: 1.4.3
PackageLocale: en-US
Publisher: ais7896-hue
PublisherUrl: https://github.com/ais7896-hue
PublisherSupportUrl: https://github.com/ais7896-hue/KyteShelf/issues
PackageName: KyteShelf
PackageUrl: https://github.com/ais7896-hue/KyteShelf
License: Proprietary
LicenseUrl: https://github.com/ais7896-hue/KyteShelf/blob/main/LICENSE
Copyright: Copyright (c) 2026 ais7896-hue
ShortDescription: Lightweight and modern desktop file shelf and workspace organizer for Windows.
Description: |-
  KyteShelf is an elegant, multi-workspace desktop shelf for Windows.
  It acts as a temporary holding zone and staging area for frequently accessed files, quick drag-and-drop actions, sticky notes, and tags.
Tags:
- shelf
- desktop-shelf
- file-organizer
- productivity
- workflow
ReleaseNotesUrl: https://github.com/ais7896-hue/KyteShelf/releases/tag/v1.4.3
ManifestType: defaultLocale
ManifestVersion: 1.6.0
