# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ais7896-hue.KyteShelf
PackageVersion: 1.4.3
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
UpgradeBehavior: install
ProductCode: '{8E3C1B20-5A2C-497B-864D-0D8B6E3210F8}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ais7896-hue/KyteShelf/releases/download/v1.4.3/KyteShelf_Setup_v1.4.3.exe
  InstallerSha256: 49EA8464346D450195FA5579D75388B7EA364EB7DB05D0B3D36F28015E28BA43
ManifestType: installer
ManifestVersion: 1.6.0
