# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ais7896-hue.KyteRename
PackageVersion: 1.1.3
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
UpgradeBehavior: install
ProductCode: '{5E6F7A8B-9C0D-1E2F-3A4B-5C6D7E8F9A0B}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ais7896-hue/KyteRename/releases/download/v1.1.3/KyteRename_Setup_1.1.3.exe
  InstallerSha256: 4618DA6B40608D8A1917135F26145F8AAB1898C271E749B503681A56B473BED9
ManifestType: installer
ManifestVersion: 1.6.0
