# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ais7896-hue.KyteView
PackageVersion: 1.5.2
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
  SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
UpgradeBehavior: install
ProductCode: '{9F7B18E3-4B82-4160-84E3-8E1E7D173981}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ais7896-hue/KyteView/releases/download/v1.5.2/KyteView_Setup_1.5.2.exe
  InstallerSha256: 6AB4F4F7AA5310D2BCBFDE917958E813AC6F0B6731177F5EE4FA2C1D62AA5864
ManifestType: installer
ManifestVersion: 1.6.0
